version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: api_albion_app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www

  web:
    image: nginx:alpine
    container_name: api_albion_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0.17
    container_name: api_albion_mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "3306:3306"
    command: --lower_case_table_names=1

volumes:
  db_data: